### ISSUE TITLE
Rage not being picked up by plugins?

### ISSUE THREAD

**Issue by ShaanMeisterr** [Queuete/ExileApi#126]
Did rage get moved out of buffs/location?

https://imgur.com/a/KaupTQc

**Comment by Queuete** [comment]
Due to rage still appearing as buff I doubt this. On the other hand it got some functionality which is closer to a resource (see chainbreaker changes).
Its obviously possible, I have looked shortly after the league start in the region of the "LifeComponent" (which should rather be named ResourcesComponent) and found nothing.

**Comment by mrm000cow** [comment]
I think what your seeing in that picture is just an incorrect offset for buff charges. @ShaanMeisterr are you having a larger issue with rage as a resource or just the buff itself?

**Comment by ShaanMeisterr** [comment]
Thanks, its been fixed now.
