### ISSUE TITLE
Latest update tagged as trojan

### ISSUE THREAD

**Issue by deMathias** [Queuete/ExileApi#151]
![image](https://user-images.githubusercontent.com/47175867/116281099-a5443180-a789-11eb-85c5-0c4e73c69d4f.png)

**Comment by Queuete** [comment]
The program is open source, you can compile it yourself if you dont trust the releases (which is totally fine). There are multiple things this program does which an AV could detect as harmful e.g.:
- accessing your mouse / keyboard
- forcing itself to be rendered above other applications
- downloading repositories, compiling them and running the resulting .dll's

It gets flagged by quite a few AV vendors since at least 6 month.
