### ISSUE TITLE
Heavy Performence Issues in Ultimatum due to EntityListWrapper.OnlyValidEntitys ?

### ISSUE THREAD

**Issue by totalschaden** [Queuete/ExileApi#164]
Killing alot of Entitys in Ultimatum basicly crashes the Hud's performence until you restart it.
There are several secs. the Hud will be unresponsive, not drawing, not using Flask, not using Skills, nothing. Then it works again a few frames, then goes back to unresponsive.

I noticed EntityListWrapper.OnlyValidEntitys goes from 500+ to Empty (loop) while deltatime is either normal or 500-1000.
Im not sure if it is related to the EntityWrapper, but i gues its a good start for investigation.

![Picture](https://i.imgur.com/xI2cHyw.png)
![Picture](https://i.imgur.com/CyONBxY.png)

**Comment by Queuete** [comment]
Thanks I will look into that one.

This potentially results in a slightly bigger rework of the EntityListWrapper I had in mind for quite some time.

**Comment by Queuete** [comment]
The current preview is in this branch: https://github.com/Queuete/ExileApi/tree/bugfix_%23164_entity_collection

I have to do a bit more testing and performance comparison before I merge this into master.

Furthermore the useage of "invalid" entities is different from the current implementation. Most of them are completly removed from the Entities as soon as they are deteced as invalid. Invalid are those entities which addresses are no longer part of the Entity list in the game. I am currently not entirely sure if I want to keep the old behaviour or stay with the one in the new branch.

**Comment by Queuete** [comment]
@totalschaden do you have SimplePickIt activated?

**Comment by totalschaden** [comment]
> 
> 
> @totalschaden do you have SimplePickIt activated?

Yes, I have it active.

Ive noticed something that dosnt realy makes sense to me too, I had the game running in Dx11 mode for some reason. After noticing I changed it back to vulcan, and while I use capped fps in both (Good Hardware, always Capped in both), the problem is almost non existend when i run vulcan. It may have a increased tick time here and there in ultimatum but its not getting unresponsive for several secs, nor is it stacking up as a permanent problem that forces a restart.

**Comment by Queuete** [comment]
SimplePickIt had major performance impact when there were a lot of items (e.g. after ultimatum). There was an update which reduced the load by a lot. The logic now is only executed when the pick up button is pressed (instead of all the time in the background) and there is a customizeable delay between 2 executions of the code which gathers the next 10 items to pick.

The EntityList was reworked. The performance should be slightly increased, a ConcurrentDictionary is used and most of the code got simplyfied. The "IsValid" property behaves slightly different to the version before. Entities which are not part of the current (Poe memory) entity list are removed from the collection instead of set to "!IsValid".

**Comment by vadash** [comment]
I use https://github.com/vadash/Pickit with community

**Comment by vadash** [comment]
> SimplePickIt had major performance impact when there were a lot of items (e.g. after ultimatum). There was an update which reduced the load by a lot. The logic now is only executed when the pick up button is pressed (instead of all the time in the background) and there is a customizeable delay between 2 executions of the code which gathers the next 10 items to pick.
> 
> The EntityList was reworked. The performance should be slightly increased, a ConcurrentDictionary is used and most of the code got simplyfied. The "IsValid" property behaves slightly different to the version before. Entities which are not part of the current (Poe memory) entity list are removed from the collection instead of set to "!IsValid".

Concurrent is great. for each dont block and has same performance as normal dic. just make sure never call .Count or .Values

**Comment by Queuete** [comment]
@vadash to get the values threadsafe from the concurrent dictionary you need to first get a "snapshot" from it with .toArray().

Overall those threadsafe collections do have quite a few pitfalls. Every method which comes through an interface (e.g. IDictionary, ICollection etc.) is not guaranteed to be threadsafe.
Methods are threadsafe: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?redirectedfrom=MSDN&view=net-5.0#methods
Those are not: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?redirectedfrom=MSDN&view=net-5.0#explicit-interface-implementations

I am not entirely sure the current implementation (especially of the derived collections Entities, OnlyValidEntities) is perfect in that regard.

**Comment by totalschaden** [comment]
> 
> 
> @vadash to get the values threadsafe from the concurrent dictionary you need to first get a "snapshot" from it with .toArray().
> 
> Overall those threadsafe collections do have quite a few pitfalls. Every method which comes through an interface (e.g. IDictionary, ICollection etc.) is not guaranteed to be threadsafe.
> Methods are threadsafe: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?redirectedfrom=MSDN&view=net-5.0#methods
> Those are not: https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?redirectedfrom=MSDN&view=net-5.0#explicit-interface-implementations
> 
> I am not entirely sure the current implementation (especially of the derived collections Entities, OnlyValidEntities) is perfect in that regard.

Had Huge frametimes/Deltatime with Multithread Settings in Hud yesterday evening (version), had to disable it all to get good values. Using Multithreaded in Mapicons for example broke the entire Plugin.

**Comment by Queuete** [comment]
MinimapIcons "multithread" is not really adding value. If you have multiple Cores assigned in the main configuration it should run the logic the same way regardless of your settings.

But there are certainly some bugs in the current "MultiThreadManager" partly probably the result of distinguishing between "Single Thread" and "Multi thread" instead of making the Multithread logic able to run on any amount of cores (including 1)

To show the plugin load you need to check the "Debug Information" option in the main menu.
![grafik](https://user-images.githubusercontent.com/62324681/118393812-4879bf80-b641-11eb-9840-6a1bc3617ae3.png)
