### ISSUE TITLE
offset issue

### ISSUE THREAD

**Issue by kzeratal** [Queuete/ExileApi#314]
Hi, your api is amazing, thank you for sharing this.
I'd like to know if it is available in garena server.
I've tried to find some pointers myself, I started from `HP`, `MP`, and they read memory very well.
But when it comes to inventory item, things are getting harder.
I need a little help about how to find the correct pointer of inventory.
I've tried to move item and search the position changed value, or use alteration orb to change the mods, but there is no luck. I can't get a correct pointer. I now stucked. any advices please?

**Comment by snowhawk04** [comment]
> I'd like to know if it is available in garena server.

I don't believe I've seen anyone publicly sharing offsets for this specific project outside of the standalone international client.

> I've tried to find some pointers myself, I started from HP, MP, and they read memory very well.
But when it comes to inventory item, things are getting harder.
I need a little help about how to find the correct pointer of inventory.
I've tried to move item and search the position changed value

The player inventories can be found in ```IngameState.Data.ServerData```. The reason you cannot find it by position is because item entities are stored in a linked list

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/Core/PoEMemory/MemoryObjects/ServerInventory.cs#L29

and contiguous array (where empty slots are simply zeroed out).

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/Core/PoEMemory/MemoryObjects/ServerInventory.cs#L33-L46

> use alteration orb to change the mods

Whenever you change an object, the game creates a new instance of the entity in memory. Don't do this.

> any advices please?

The easiest way to find an inventory is to search for the number of item entities in the inventory. 

https://github.com/Queuete/ExileApi/blob/master/GameOffsets/ServerInventoryOffsets.cs#16

Once you have the address of the `int` that stores the count, you can listen for what accesses that address and backtrack to `IngameState` from there.

**Comment by Queuete** [comment]
@kzeratal Sorry but a Garena version is not available or planned. There certainly is a lot of stuff which could be used aswell, but there are at least some offset differences. 
The other questions got already answered by snowhawk, thanks!

**Comment by kzeratal** [comment]
Thanks for the reply.
It really helped me a lot!

**Comment by snowhawk04** [comment]
> I tried further trace the Entity of InventSlotItem, and I don't know if it is the correct way to do it.

This really just comes down to a familiarity of the underlying components of data structures. In this case, it's just a tree of nodes with a root node. Each node is structured with a pointer to the previous, parent, and next nodes. In the root node, the parent node holds the address of a null ending node that leaf nodes point to.

Payload-wise, there is a bool to tell you if there is an index and key being held or not. if there isn't, the remaining data is just garbage.

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/GameOffsets/Native/NativeHashNode.cs#L13-L18

As for the `InventSlotItem`, you could trace using the slot positions. 

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/Core/PoEMemory/MemoryObjects/ServerInventory.cs#L114

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/Core/PoEMemory/MemoryObjects/ServerInventory.cs#L137-L140

Consider the player inventory. If an amulet (width 1, height 1) is in the first inventory slot (x 0, y 0), you can byte array search the `Xmin, Ymin, Xmax, Ymax` 

```00 00 00 00 00 00 00 00 01 00 00 00 01 00 00 00```

If it were a 2h axe (width 2, height 4) in the bottom right corner, the min max values would be 10, 1, 12, 5 

```0A 00 00 00 01 00 00 00 0C 00 00 00 05 00 00 00```

From there, trace up the pointer stack to the tree node above.

Note: Moving items around will destroy the nodes referencing the previous inventory slot and create new nodes referencing the updated inventory slot.

> Entity seems to be designed for monsters.

Entity is any in-game object that utilizes components. The use case spawns multiple domains. See `Entity.ParseType()`

https://github.com/Queuete/ExileApi/blob/2f01a421fa0755cfc57773e58ab94cdc552e6b77/Core/PoEMemory/MemoryObjects/Entity.cs#L561

**Comment by kzeratal** [comment]
> 
> Entity is any in-game object that utilizes components. The use case spawns multiple domains. See `Entity.ParseType()`
> 

I finally figured it out, mod and other components are accessed by generic method `GetComponent<T>`.
So I spent a day to trace further deep.
Now I'm able to get the first mod of the first slot item in the player inventory.

![image](https://user-images.githubusercontent.com/20305449/166450948-6c7697a3-6ada-40c9-b2ec-89c456d69c57.png)

Offsets are correct, It saves me a lot of time.
The last thing to do is dealing with array!
