### ISSUE TITLE
For Steam users

### ISSUE THREAD

**Issue by olaims** [Queuete/ExileApi#91]
Hello, inside the "Core.cs", the function "FindPoeProcess", you have to add the line 

clients.AddRange(Process.GetProcessesByName(Offsets.Steam.ExeName).Select(p => (p, Offsets.Steam)));

without adding it the steam process will be never be found ;)

**Comment by Queuete** [comment]
Have you compiled it and tested it? I am 99% sure there are quite a few more differences between steam and the native client. At least the base offsets used to have more differences. 
If you want to work that out, feel free to make a pull request and I will include that. Otherwise this will keep supporting the native client only most likely.

**Comment by olaims** [comment]
Jup tested, but I cannot see and/or load any plugin.... so it is quite useless :( 

When I add a plugin, for example, "Stashi", I get errors on the imports from the "ExileCore" library. Maybe I'm doing something wrong there... but I can just get working the Hud (I can change the settings and so on).

I also don't know how it works that "add plugin" inside the interface. Should I put the git URL? my local path? none of both works :D

**Comment by Queuete** [comment]
There is a plugin configuration by default which shows that you need git urls to add a plugin. 
If you open the log you will most likely see more errors about offsets not found.
